export enum CATEGORIES_ACTION_TYPE{
    SET_CATEGORIES_MAP='category/SET_CATEGORIES_MAP',
    SET_CATEGORIES='category/SET_CATEGORIES_MAP',
    FETCH_CATEGORIES_FAILED='category/FETCH_CATEGORIES_FAILED',
    FETCH_CATEGORIES_LOADING='category/FETCH_CATEGORIES_LOADING',
}